/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Farrukhjon' at '9/25/15 2:35 PM' with Gradle 2.5
 *
 * @author Farrukhjon, @date 9/25/15 2:35 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
