apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandra
spec:
  type: NodePort
  ports:
    - name: cassandra
      nodePort: 30042
      port: 9042
      targetPort: 9042
  selector:
    app: cassandra

